version: '3'

services:
    metadata-service:
        image: leanda/metadata-processing:${TAG_VERSION-latest}
        build:
            context: .
            dockerfile: Sds.MetadataStorage.Processing/Dockerfile

    tests:
        image: leanda/metadata-processing-tests:${TAG_VERSION-latest}
        build:
            context: .
            dockerfile: Sds.MetadataStorage.Tests/Dockerfile

networks:
    leanda-ext:
        external:
            name: leanda-ext
